name: TundereBackup
main: net.tsuttsu305.tunderebackup.TundereBackup
version: 1.0.0
author: tsuttsu305
commands:
  backup:
    description: BackupCommand
    permission: tunderebackup.backup
    usage: /backup - Backup Now
permissions:
  tunderebackup.*:
    description: Gives all Access
    children:
      tunderebackup.backup: true
      tunderebackup.reload: true
  tunderebackup.backup:
    description: Backup Now
    default: OP
  tunderebackup.reload:
    description: reload config
    default: OP